//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_entity_framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> StudentAge { get; set; }
        public string StudentGender { get; set; }
        public string StudentAddress { get; set; }
        public Nullable<int> FacultyID { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
